### PR TITLE
Add missing long for py2 and autoescape escape codes from filepaths in windows

### PR DESCRIPTION
**Pull request by Hellowlol**

### CODE REVIEW

**Comment by idlesign** [comment]
Thank you.
Please take a notice that some tests are failed on py3. This should be imporved before merge.
Coverage is dropped too, so consider adding new tests.

**Comment by Hellowlol** [comment]
I can add some new tests however for this to work we need a bigger file so the filesize is long on python 2.  Also tests for test_getters_dir and create_torrent fails on windows (unrelated to the pr)

**Comment by idlesign** [comment]
Great!

> [...] we need a bigger file so the filesize [...]

Probably some kind of mock will do instead of a real file.

As for dir tests, if you have time you could fix it, as I have no Windows to check that out.

**Comment by Hellowlol** [comment]
I would like to get rid for .api file and just import it in the init file.  I would like to redo all the test and use pytest as i dont like unittest.  I just wanted to check if this is something you would accept before i start on a pr.

**Comment by idlesign** [comment]
- You can import base classes in init, but api.py should be kept intact for now as a self-describing entry-point and for backward compatibility reasons.
- pytest is certainly welcome.

**Comment by Hellowlol** [comment]
Awesome, thanks!

**Comment by Hellowlol** [comment]
Sorry for being a couchpotato. Ill fixup the windows test and send a new pr. Thanks for pytest commit. Saved me alot of work :P

**Comment by idlesign** [comment]
That's ok, pull requests are welcome %)

**Pull request closed without merging**
